[package]
name = "systemd_service_parser"
description = "A simple systemd service file parser"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.7.14"
pest_derive = "2.7.14"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
